# Grid world parameters
GRID_SIZE = 5
START_POS = (0, 0)
TARGET_POS = (2, 3)
FORBIDDEN_CELLS = [(1, 1), (1, 3), (2, 1), (2, 2), (3, 3)]

# GRID_SIZE = 3
# START_POS = (0, 0)
# TARGET_POS = (2, 2)
# FORBIDDEN_CELLS = [(0, 2), (2, 1)]

# Reward parameters
REWARD_TARGET = 1
REWARD_BOUNDARY = -1
REWARD_FORBIDDEN = -1
REWARD_STEP = 0

# RL parameters 
SHOW_GRID_WORLD = True

# REINFORCE
REINFORCE_SEED = 42

REINFORCE_NET_SIZE = 128

REINFORCE_GAMMA = 0.95
REINFORCE_LR = 2e-4
REINFORCE_EPISODE = 50000
REINFORCE_MAX_EPISODE_LENGTH = 100