# Grid world parameters
GRID_SIZE = 5
GOAL_POS = (2, 3)
FORBIDDEN_CELLS = [(1, 1), (1, 3), (1, 4), (2, 1), (2, 2), (3, 3)]

# Reward parameters
REWARD_TARGET = 1
REWARD_BOUNDARY = -1
REWARD_FORBIDDEN = -1
REWARD_STEP = 0

# RL parameters
SHOW_GRID_WORLD = True
DISCOUNT_FACTOR = 0.9
VALUE_ITERATION_THRESHOLD = 1e-4
MAX_EPISODE_STEPS = 100