# Monte Carlo specific parameters

# Grid world parameters
GRID_SIZE = 5
GOAL_POS = (2, 3)
FORBIDDEN_CELLS = [(1, 1), (1, 3), (1, 4), (2, 1), (2, 2), (3, 3)]

# Reward parameters
REWARD_TARGET = 5
REWARD_BOUNDARY = -1
REWARD_FORBIDDEN = -10
REWARD_STEP = 0

# RL parameters
SHOW_GRID_WORLD = True

# Monte Carlo parameters
MC_BASIC_DISCOUNT_FACTOR = 0.9
MC_VALUE_ESTIMATION_THRESHOLD = 1e-4
MC_VALUE_ESTIMATION_MAX_ITERATE_STEPS = 1000
MC_BASIC_EPISODES = 1
MC_BASIC_EPISODE_LENGTH = 20

# MC Exploring Starts parameters
MC_ES_DISCOUNT_FACTOR = 0.9
MC_ES_EPISODES = 10000
MC_ES_EPISODE_LENGTH = 200

# MC Epsilon Greedy parameters
MC_EG_DISCOUNT_FACTOR = 0.9
MC_EG_MAX_ITERATE_STEPS = 100
MC_EG_EPISODES = 100
MC_EG_EPISODE_LENGTH = 200
MC_EG_EPSILON = 0.2
MC_EG_THRESHOLD = 1e-4
