# Grid world parameters
GRID_SIZE = 5
START_POS = (0, 0)
TARGET_POS = (2, 3)
FORBIDDEN_CELLS = [(1, 1), (1, 3), (1, 4), (2, 1), (2, 2), (3, 3)]

# GRID_SIZE = 3
# START_POS = (0, 0)
# TARGET_POS = (2, 2)
# FORBIDDEN_CELLS = [(0, 2), (2, 1)]

# Reward parameters
REWARD_TARGET = 1
REWARD_BOUNDARY = -5
REWARD_FORBIDDEN = -5
REWARD_STEP = 0

# RL parameters 
# FA: Function Approximation 
SHOW_GRID_WORLD = True

# Sarsa (with FA) parameters 
SARSA_DISCOUNT_FACTOR = 0.9
SARSA_ALPHA = 0.001
SARSA_EPSILON = 0.2
Q_LEARNING_EPISODES = 500
SARSA_MAX_EPISODE_LENGTH = 1000

# Q-learning (with FA) parameters
Q_LEARNING_DISCOUNT_FACTOR = 0.9
Q_LEARNING_EPSILON = 0.1
Q_LEARNING_ALPHA = 0.001
Q_LEARNING_EPISODES = 500
Q_LEARNING_EPISODE_LENGTH = 1000

# DQN parameters
DQN_SEED = 42

DQN_HIDDEN_SIZE = 100

DQN_EPISODE = 200
DQN_EPISODE_MAX_LENGTH = 500
DQN_REPLAY_CAPACITY = 50000

DQN_BATCH_SIZE = 32
DQN_TRAINING_EPOCH = 200

DQN_LR = 4e-3
DQN_DISCOUNT_FACTOR = 0.9
DQN_TARGET_UPDATE_FREQ = 20
